In [21]:
import numpy as np
import pandas as pd
import scipy
import sklearn as skl
# from tqdm.notebook import tqdm

from tqdm import tqdm
import rich

In [22]:
import kagglehub
import pathlib

path = kagglehub.dataset_download("shubhammehta21/movie-lens-small-latest-dataset")

movies_df = pd.read_csv(pathlib.Path(path) / "movies.csv")
ratings_df = pd.read_csv(pathlib.Path(path) / "ratings.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.8), please consider upgrading to the latest version (0.3.12).

In [23]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [24]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [25]:
ratings_df["rating"].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [26]:
sparce_ratings_df = (
    ratings_df.pivot_table(index="userId", columns="movieId", values="rating")
    .fillna(0)
    .astype(pd.SparseDtype("float", fill_value=0.0))
)
sparce_ratings_df

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
from sklearn.model_selection import train_test_split

R_train, R_test = train_test_split(
    ratings_df,
    test_size=0.2,
)

In [28]:
R_train = (
    R_train.pivot_table(index="userId", columns="movieId", values="rating")
    .fillna(0)
    .astype(pd.SparseDtype("float", fill_value=0.0))
)

R_test = (
    R_test.pivot_table(index="userId", columns="movieId", values="rating")
    .fillna(0)
    .astype(pd.SparseDtype("float", fill_value=0.0))
)

In [31]:
import scipy.sparse


class CollaborateFiltrator:  # latent factor model
    def fit(
        self,
        R: scipy.sparse.csr_matrix,
        R_test: scipy.sparse.csr_matrix,
        k: int = 13,
        epochs: int = 20,
    ) -> np.ndarray:
        m, n = R.shape

        rows, cols = R.nonzero()

        eta, lambda_ = 0.01, 0.1

        P = np.random.rand(m, k) * 0.01
        Q = np.random.rand(n, k) * 0.01
        e: scipy.sparse.csr_matrix = R.copy()

        for epoch in range(epochs):
            with tqdm(
                total=len(rows),
                desc=f"Epoch {epoch + 1}/{epochs}",
                ncols=150,
                colour="cyan",
                leave=True,
            ) as epoch_bar:
                for user_id, object_id in zip(rows, cols):
                    e[user_id, object_id] = R[user_id, object_id] - np.dot(
                        P[user_id, :], Q[object_id, :]
                    )

                    p, q = P[user_id, :].copy(), Q[object_id, :].copy()

                    P[user_id, :] += eta * (e[user_id, object_id] * q - lambda_ * p)
                    Q[object_id, :] += eta * (e[user_id, object_id] * p - lambda_ * q)
                    epoch_bar.update(1)
                else:
                    loss = (e.multiply(e)).sum() + (
                        np.linalg.norm(P) ** 2 + np.linalg.norm(Q) ** 2
                    )
                    self.P = P
                    self.Q = Q

                    r_pred = self.predict(*R_test.nonzero())

                    mae = (R_test - r_pred).__abs__().sum() / (R.count_nonzero())
                    rmse = np.sqrt(
                        (R_test - r_pred).multiply(R_test - r_pred).sum()
                        / R.count_nonzero()
                    )

                    epoch_bar.set_postfix(
                        {
                            "loss": f"{loss:.6f}",
                            "MAE": f"{mae:.6f}",
                            "RMSE": f"{rmse:.6f}",
                        }
                    )
                    epoch_bar.update(0)

        self.P = P
        self.Q = Q
        self.m = m
        self.user_count = self.m
        self.n = n
        self.object_count = self.n
        self.k = k
        self.latent_space = self.k

    def predict(
        self, user_ids: list[int] | np.ndarray, object_ids: list[int] | np.ndarray
    ) -> np.ndarray:
        score = np.zeros(shape=(len(user_ids),), dtype=np.float32)
        for idx, [user_id, object_id] in enumerate(zip(user_ids, object_ids)):
            score[idx] = np.dot(self.P[user_id], self.Q[object_id])
        return scipy.sparse.csr_matrix(
            (
                score,
                (
                    np.array(user_ids, dtype=np.int32),
                    np.array(object_ids, dtype=np.int32),
                ),
            ),
            dtype=np.float32,
        )


spread = 5 - 1


filtrator = CollaborateFiltrator()
filtrator.fit(
    R_train.sparse.to_coo().tocsr(),
    R_test.sparse.to_coo().tocsr(),
    k=37,
    epochs=23,
)

Epoch 1/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 21714.81it/s, loss=842676.461541, MAE=0.807896, RMSE=1.707889]
Epoch 2/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 21374.71it/s, loss=334135.364749, MAE=0.613941, RMSE=1.372381]
Epoch 3/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20990.80it/s, loss=171548.474122, MAE=0.508227, RMSE=1.179739]
Epoch 4/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 21024.86it/s, loss=128717.223984, MAE=0.447641, RMSE=1.063608]
Epoch 5/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20523.98it/s, loss=110273.543684, MAE=0.408840, RMSE=0.985794]
Epoch 6/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19878.19it/s, loss=100172.782038, MAE=0.382468, RMSE=0.930303]
Epoch 7/23: 100%|████████████████████████████████████████████| 80668/80668 [00:04<00:00, 19748.65it/s, loss=93886.686194, MAE=0.363475, RMSE=0.889006]
Epoch 8/23: 100%|████████████████████████████████████████████| 80668/80668 [00:03<00:00, 20239.45it/s, loss=89650.651915, MAE=0.349269, RMSE=0.857267]
Epoch 9/23: 100%|████████████████████████████████████████████| 80668/80668 [00:03<00:00, 20227.08it/s, loss=86641.738529, MAE=0.338231, RMSE=0.832233]
Epoch 10/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20710.02it/s, loss=84424.946833, MAE=0.329405, RMSE=0.812050]
Epoch 11/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20273.25it/s, loss=82748.282179, MAE=0.322220, RMSE=0.795474]
Epoch 12/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19933.82it/s, loss=81455.447020, MAE=0.316268, RMSE=0.781636]
Epoch 13/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19845.99it/s, loss=80444.287073, MAE=0.311253, RMSE=0.769922]
Epoch 14/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 20095.24it/s, loss=79645.197533, MAE=0.306966, RMSE=0.759885]
Epoch 15/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19966.46it/s, loss=79009.099906, MAE=0.303247, RMSE=0.751193]
Epoch 16/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20259.65it/s, loss=78500.372984, MAE=0.300000, RMSE=0.743597]
Epoch 17/23: 100%|███████████████████████████████████████████| 80668/80668 [00:03<00:00, 20171.54it/s, loss=78092.509343, MAE=0.297148, RMSE=0.736907]
Epoch 18/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19293.59it/s, loss=77765.345945, MAE=0.294611, RMSE=0.730973]
Epoch 19/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 18926.16it/s, loss=77503.240693, MAE=0.292335, RMSE=0.725679]
Epoch 20/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 18481.11it/s, loss=77293.836906, MAE=0.290278, RMSE=0.720931]
Epoch 21/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19100.90it/s, loss=77127.204013, MAE=0.288430, RMSE=0.716653]
Epoch 22/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 19248.05it/s, loss=76995.225213, MAE=0.286753, RMSE=0.712783]
Epoch 23/23: 100%|███████████████████████████████████████████| 80668/80668 [00:04<00:00, 18793.65it/s, loss=76891.150738, MAE=0.285226, RMSE=0.709269]

In [33]:
R_test

movieId,1,2,3,4,5,6,7,9,10,11,...,185135,187541,187593,187595,187717,188675,189333,193573,193579,193581
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import cross_validate

reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(ratings_df[["userId", "movieId", "rating"]], reader)

# Обучение и оценка
surprise_filtrator = SVD(
    n_factors=37,
    biased=True,
)
print(
    cross_validate(
        surprise_filtrator,
        data,
        measures=["RMSE", "MAE"],
        cv=5,
        verbose=True,
    )
)

TypeError: cross_validate() got an unexpected keyword argument 'epoch'

In [47]:
print(SVD.__doc__)

The famous *SVD* algorithm, as popularized by `Simon Funk
    <https://sifter.org/~simon/journal/20061211.html>`_ during the Netflix
    Prize. When baselines are not used, this is equivalent to Probabilistic
    Matrix Factorization :cite:`salakhutdinov2008a` (see :ref:`note
    <unbiased_note>` below).

    The prediction :math:`\hat{r}_{ui}` is set as:

    .. math::
        \hat{r}_{ui} = \mu + b_u + b_i + q_i^Tp_u

    If user :math:`u` is unknown, then the bias :math:`b_u` and the factors
    :math:`p_u` are assumed to be zero. The same applies for item :math:`i`
    with :math:`b_i` and :math:`q_i`.

    For details, see equation (5) from :cite:`Koren:2009`. See also
    :cite:`Ricci:2010`, section 5.3.1.

    To estimate all the unknown, we minimize the following regularized squared
    error:

    .. math::
        \sum_{r_{ui} \in R_{train}} \left(r_{ui} - \hat{r}_{ui} \right)^2 +
        \lambda\left(b_i^2 + b_u^2 + ||q_i||^2 + ||p_u||^2\right)


    The minimization is performed by a very straightforward stochastic gradient
    descent:

    .. math::
        b_u &\leftarrow b_u &+ \gamma (e_{ui} - \lambda b_u)\\
        b_i &\leftarrow b_i &+ \gamma (e_{ui} - \lambda b_i)\\
        p_u &\leftarrow p_u &+ \gamma (e_{ui} \cdot q_i - \lambda p_u)\\
        q_i &\leftarrow q_i &+ \gamma (e_{ui} \cdot p_u - \lambda q_i)

    where :math:`e_{ui} = r_{ui} - \hat{r}_{ui}`. These steps are performed
    over all the ratings of the trainset and repeated ``n_epochs`` times.
    Baselines are initialized to ``0``. User and item factors are randomly
    initialized according to a normal distribution, which can be tuned using
    the ``init_mean`` and ``init_std_dev`` parameters.

    You also have control over the learning rate :math:`\gamma` and the
    regularization term :math:`\lambda`. Both can be different for each
    kind of parameter (see below). By default, learning rates are set to
    ``0.005`` and regularization terms are set to ``0.02``.

    .. _unbiased_note:

    .. note::
        You can choose to use an unbiased version of this algorithm, simply
        predicting:

        .. math::
            \hat{r}_{ui} = q_i^Tp_u

        This is equivalent to Probabilistic Matrix Factorization
        (:cite:`salakhutdinov2008a`, section 2) and can be achieved by setting
        the ``biased`` parameter to ``False``.


    Args:
        n_factors: The number of factors. Default is ``100``.
        n_epochs: The number of iteration of the SGD procedure. Default is
            ``20``.
        biased(bool): Whether to use baselines (or biases). See :ref:`note
            <unbiased_note>` above.  Default is ``True``.
        init_mean: The mean of the normal distribution for factor vectors
            initialization. Default is ``0``.
        init_std_dev: The standard deviation of the normal distribution for
            factor vectors initialization. Default is ``0.1``.
        lr_all: The learning rate for all parameters. Default is ``0.005``.
        reg_all: The regularization term for all parameters. Default is
            ``0.02``.
        lr_bu: The learning rate for :math:`b_u`. Takes precedence over
            ``lr_all`` if set. Default is ``None``.
        lr_bi: The learning rate for :math:`b_i`. Takes precedence over
            ``lr_all`` if set. Default is ``None``.
        lr_pu: The learning rate for :math:`p_u`. Takes precedence over
            ``lr_all`` if set. Default is ``None``.
        lr_qi: The learning rate for :math:`q_i`. Takes precedence over
            ``lr_all`` if set. Default is ``None``.
        reg_bu: The regularization term for :math:`b_u`. Takes precedence
            over ``reg_all`` if set. Default is ``None``.
        reg_bi: The regularization term for :math:`b_i`. Takes precedence
            over ``reg_all`` if set. Default is ``None``.
        reg_pu: The regularization term for :math:`p_u`. Takes precedence
            over ``reg_all`` if set. Default is ``None``.
        reg_qi: The regularization term for :math:`q_i`. Takes precedence
            over ``reg_all`` if set. Default is ``None``.
        random_state(int, RandomState instance from numpy, or ``None``):
            Determines the RNG that will be used for initialization. If
            int, ``random_state`` will be used as a seed for a new RNG. This is
            useful to get the same initialization over multiple calls to
            ``fit()``.  If RandomState instance, this same instance is used as
            RNG. If ``None``, the current RNG from numpy is used.  Default is
            ``None``.
        verbose: If ``True``, prints the current epoch. Default is ``False``.

    Attributes:
        pu(numpy array of size (n_users, n_factors)): The user factors (only
            exists if ``fit()`` has been called)
        qi(numpy array of size (n_items, n_factors)): The item factors (only
            exists if ``fit()`` has been called)
        bu(numpy array of size (n_users)): The user biases (only
            exists if ``fit()`` has been called)
        bi(numpy array of size (n_items)): The item biases (only
            exists if ``fit()`` has been called)